name: mq-producer
kind: pipeline
type: kubernetes

steps:
  #- name: Test kubectl 
  #  image: rancher/kubectl:v1.23.7
  #  commands:
  #    - kubectl apply -f image-builder.yaml
  - name: Image build
    image: quay.io/buildah/stable:latest
    commands:
      - buildah bud --layers=true --tag producer:test ./backend/mq/producer