name: mq-producer
kind: pipeline
type: kubernetes

steps:
  - name: build image
    image: quay.io/buildah/stable
    commands:
      - buildah bud --layers=true --tag  harbor.adamkoro.com/demo-k8s/producer:test backend/mq/producer